// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: regulator.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RegulatorService_StoreToController_FullMethodName = "/controller.RegulatorService/StoreToController"
)

// RegulatorServiceClient is the client API for RegulatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegulatorServiceClient interface {
	StoreToController(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type regulatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRegulatorServiceClient(cc grpc.ClientConnInterface) RegulatorServiceClient {
	return &regulatorServiceClient{cc}
}

func (c *regulatorServiceClient) StoreToController(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RegulatorService_StoreToController_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegulatorServiceServer is the server API for RegulatorService service.
// All implementations must embed UnimplementedRegulatorServiceServer
// for forward compatibility.
type RegulatorServiceServer interface {
	StoreToController(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedRegulatorServiceServer()
}

// UnimplementedRegulatorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRegulatorServiceServer struct{}

func (UnimplementedRegulatorServiceServer) StoreToController(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreToController not implemented")
}
func (UnimplementedRegulatorServiceServer) mustEmbedUnimplementedRegulatorServiceServer() {}
func (UnimplementedRegulatorServiceServer) testEmbeddedByValue()                          {}

// UnsafeRegulatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegulatorServiceServer will
// result in compilation errors.
type UnsafeRegulatorServiceServer interface {
	mustEmbedUnimplementedRegulatorServiceServer()
}

func RegisterRegulatorServiceServer(s grpc.ServiceRegistrar, srv RegulatorServiceServer) {
	// If the following call pancis, it indicates UnimplementedRegulatorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RegulatorService_ServiceDesc, srv)
}

func _RegulatorService_StoreToController_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegulatorServiceServer).StoreToController(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegulatorService_StoreToController_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegulatorServiceServer).StoreToController(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// RegulatorService_ServiceDesc is the grpc.ServiceDesc for RegulatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegulatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "controller.RegulatorService",
	HandlerType: (*RegulatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreToController",
			Handler:    _RegulatorService_StoreToController_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "regulator.proto",
}
